# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-base"
BBFILE_PATTERN_meta-base = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-base = "6"

LAYERDEPENDS_meta-base = "core"
LAYERSERIES_COMPAT_meta-base = "scarthgap"
